#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================
ynh_script_progression --message="Loading installation settings..."

app=$YNH_APP_INSTANCE_NAME

config_path=$(ynh_app_setting_get --app=$app --key=config_path)

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE SERVICE FROM ADMIN PANEL
#=================================================

# Remove a service from the admin panel, added by `yunohost service add`
if yunohost service status $app >/dev/null 2>&1
then
	ynh_script_progression --message="Removing $app service"
	yunohost service remove $app
fi

#=================================================
# UNREGISTER ALL RUNNERS
#=================================================
ynh_script_progression --message="Unregistering all runners..."

ynh_exec_warn_less $app unregister --all-runners

#=================================================
# REMOVE GITLAB RUNNER
#=================================================
ynh_script_progression --message="Removing Gitlab Runner"

dpkg --remove $app

#=================================================
# REMOVE DEPENDENCIES
#=================================================
ynh_script_progression --message="Removing dependencies"

# Remove metapackage and its dependencies
ynh_remove_app_dependencies

#=================================================
# REMOVE APP CONFIG DIR
#=================================================
ynh_script_progression --message="Removing app config directory"

ynh_secure_remove --file="$config_path"

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Removing a repo..."

ynh_remove_extra_repo --name="${app}-docker"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
