#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

new_gitlab_url=${YNH_ACTION_GITLAB_URL}
new_token=${YNH_ACTION_TOKEN}
new_docker_image=${YNH_ACTION_DOCKER_IMAGE}

app=${YNH_APP_INSTANCE_NAME:-$YNH_APP_ID}

gitlab_url=$(ynh_app_setting_get --app=$app --key=gitlab_url)
token=$(ynh_app_setting_get --app=$app --key=token)
docker_image=$(ynh_app_setting_get --app=$app --key=docker_image)
executor=$(ynh_app_setting_get --app=$app --key=executor)
architecture=$(ynh_app_setting_get --app=$app --key=architecture)

#=================================================
# CHECK IF ARGUMENTS ARE CORRECT
#=================================================

# Adding a comma at the end
if [ ${new_gitlab_url: -1} != "," ]; then
	new_gitlab_url=${new_gitlab_url},
fi

# Adding a comma at the end
if [ ${new_token: -1} != "," ]; then
	new_token=${new_token},
fi

# Adding a comma at the end
if [ ${new_docker_image: -1} != "," ]; then
	new_docker_image=${new_docker_image},
fi

#=================================================
# BACKUP BEFORE ACTION THEN ACTIVE TRAP
#=================================================
ynh_script_progression --message="Backing up the app before action (may take a while)..."

# Backup the current version of the app
ynh_backup_before_action
ynh_clean_setup () {
	# restore it if the action fails
	ynh_restore_actionbackup
}
# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# CHECK IF AN ACTION HAS TO BE DONE
#=================================================


#=================================================
# SPECIFIC ACTION
#=================================================
# REGISTER THE RUNNER
#=================================================
ynh_script_progression --message="Register GitLab Runner..."

# Can be registered several time, to do this give a list of gitlab_url, token and docker_image separated by a comma.
split_char=","

nb_to_register=$(echo "${new_gitlab_url}" | awk -F"${split_char}" '{print NF-1}')

for i in $(seq $nb_to_register)
do
	url=$(echo $new_gitlab_url | cut -d$split_char -f$i)
	tok=$(echo $new_token | cut -d$split_char -f$i)
	docker_img=$(echo $new_docker_image | cut -d$split_char -f$i)

	# Register the runner
	ynh_exec_warn_less $app register \
		--non-interactive \
		--url "$url" \
		--registration-token "$tok" \
		--executor "$executor" \
		--docker-image "$docker_img" \
		--description "Yunohost runner" \
		--tag-list "$executor,$YNH_ARCH" \
		--run-untagged \
		--locked="false"

	gitlab_url=${gitlab_url}${url},
	token=${token}${tok},
	docker_image=${docker_image}${docker_img},
done

#=================================================
# STORE SETTINGS
#=================================================
ynh_script_progression --message="Storing settings..."

ynh_app_setting_set --app=$app --key=gitlab_url --value=$gitlab_url
ynh_app_setting_set --app=$app --key=token --value=$token
ynh_app_setting_set --app=$app --key=docker_image --value=$docker_image

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Action of $app completed" --last
